config/routes.rb
Rails.application.routes.draw do
  resources :gossips do
    resources :likes, only: [:new, :create, :destroy]
  end
  resources :comments


  resources :users, only: [:show, :new, :create]
  resources :sessions, only: [:new, :create, :destroy]
  resources :cities, only: [:show]
  
  root 'gossips#index'
  get '/welcome/:id', to: 'welcome#show', as: 'welcome'
  get '/contact', to: 'welcome#contact'
  get '/team', to: 'welcome#team'

  get '/users', to: 'users#new'
  get '/sessions', to: 'sessions#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users, dependent: :delete_all
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :gossip

  validates :user,
    presence: { message: "Nous n'avons pas pu trouvé l'utilisateur associé." }

  validates :gossip,
    presence: { message: "Nous n'avons pas pu trouvé le Gossip associé." }

  validates :content,
    presence: { message: "Contenu obligatoire." }
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :join_table_tag_gossips
  has_many :tags, through: :join_table_tag_gossips
  has_many :comments
  has_many :likes, dependent: :destroy

  validates :title,
    presence: { message: "Titre obligatoire." },
    length: { minimum: 4, maximum: 60, message: "Le titre ne peut pas faire moins de 3 caractères ni plus de 60 caractères."}
  validates :content,
    presence: { message: "Contenu obligatoire." }
end

app/models/join_table_tag_gossip.rb
class JoinTableTagGossip < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :gossip

  validates :user_id,
    :uniqueness => { :scope => :gossip_id, message: "Un like par gossip" }
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :recipient, class_name: "User"
  belongs_to :sender, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :join_table_tag_gossips
  has_many :gossips, through: :join_table_tag_gossips
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :gossips
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
  has_many :comments
  has_many :likes, dependent: :destroy

  has_secure_password

  validates :first_name,
    presence: { message: "Prénom obligatoire." }

  validates :last_name,
    presence: { message: "Nom obligatoire." }

  validates :age,
    presence: { message: "Age obligatoire." }

  validates :password,
    presence: { message: "Mot de passe obligatoire." },
    length: { minimum: 6, too_short: "Mot de passe trop court." }

  validates :email,
    presence: { message: "Email obligatoire." },
    uniqueness: { message: "Email déjà pris." },
    format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "Format d'email invalide." }

  def full_name
    "#{first_name} #{last_name}"
  end

  def remember(remember_token)
    remember_digest = BCrypt::Password.create(remember_token)
    self.update(remember_digest: remember_digest)
  end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def show
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
 
  before_action :set_gossip, only: [:show, :edit, :update, :destroy]
  before_action :only_signed_in, only: [:new, :create, :edit, :update, :destroy]
  before_action :act_on_my_gossips?, only: [:edit, :update, :destroy]

  def index
    @gossip = Gossip.all
  end

  def show
    @comment = Comment.new
  end

  def new
    @gossip = Gossip.new
  end

  def create
    @gossip = Gossip.new(user: current_user, title: params[:title], content: params[:content])

    if @gossip.save
      flash[:success] = "Ton Gossip a été créé avec succès !"
      redirect_to @gossip
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @gossip.update(gossip_params)
      redirect_to @gossip, flash: {success: "Ton Gossip a été modifié avec succès !"}
    else
      render :edit
    end
  end

  def destroy
    @gossip.destroy
    flash[:danger] = "Le gossip a été supprimé."
    redirect_to gossips_path
  end

  private

  def gossip_params
    params.require(:gossip).permit(:user, :title, :content)
  end

  def set_gossip
    @gossip = Gossip.find(params[:id])
  end

  def my_gossips?
    current_user.id == set_gossip.user.id
  end

  def act_on_my_gossips?
    if !my_gossips?
      flash[:danger] = "Vous ne pouvez modifier/supprimer que vos propres Gossips."
      redirect_to @gossip
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  before_action :find_like, only: [:destroy]

  def new
    @like = Like.new
  end

  def create
    @gossip = Gossip.find(params[:gossip_id])
    @like = Like.new(gossip_id: params[:gossip_id], user: current_user)
  
    if @like.save
      redirect_to request.referrer
    else
      redirect_to request.referrer
    end
  end

  def destroy
    @like.destroy
    redirect_to request.referrer
  end

  private

  def find_like
    @gossip = Gossip.find(params[:gossip_id])
    @like = @gossip.likes.find(params[:id])
  end

  def already_liked?
    Like.where(user_id: current_user.id, gossip_id: params[:gossip_id]).exists?
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user_params = params.require(:user).permit(:first_name, :last_name, :age, :city_id, :email, :password, :password_confirmation)
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      remember(@user)
      flash[:success] = "Votre compte a été créé avec succès !"
      redirect_to root_path
    else
      render :new
    end
  end
  
  def show
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end

  def show
  end
  
  def team
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dynamic_pages_helper.rb
module DynamicPagesHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    if session[:user_id]

      current_user = User.find_by(id: session[:user_id])

    elsif cookies[:user_id]

      user = User.find_by(id: cookies[:user_id])

      if user && BCrypt::Password.new(user.remember_digest).is_password?(cookies[:remember_token])
        log_in user
        current_user = user
      end

    end
  end

   def log_in(user)
    session[:user_id] = user.id
  end

  def logged_in?
    session[:user_id]
  end

  def only_signed_in
    if !logged_in?
      flash[:danger] = "Vous devez être connecté pour cela."
      redirect_to new_session_path
    end
  end

  def current_user?(user)
    user == current_user
  end
  
  def remember(user)
    remember_token = SecureRandom.urlsafe_base64

    user.remember(remember_token)

    cookies.permanent[:user_id] = user.id
    cookies.permanent[:remember_token] = remember_token
  end

  def forget(user)
    user.update(remember_digest: nil)
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out(user)
    session.delete(:user_id)
    forget(user)
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/gossips/edit.html.erb
<html>
  <head>
  </head>
  <body>
    <% if @gossip.errors.any? %>
    <div class="alert alert-danger pt-3 pb-1 text-center" role="alert">
        <p>Nous n'avons pas réussi à modifier le gossip pour la (ou les) raison(s) suivante(s) :</p>
        <ul>
          <% @gossip.errors.each_with_index do |message, i| %>
            <li><%= message[1] %></li>
          <% end %>
        </ul>
    </div>
    <% end %>
    <div class="container text-center mt-5">
      <h1 style="color: #053557">Modifier le Gossip n°<%= @gossip.id %> ?</h1>

      <div class="m-5 px-5">
        <%= form_for @gossip do |f| %>
          <div class="form-group">
            <%= f.text_field :title, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.text_area :content, class: 'form-control' %>
          </div>
          <div class="btn-toolbar flex-nowrap justify-content-end mt-4" role="toolbar" aria-label="Toolbar with button groups">
            <div class="btn-group mr-2" role="group">
              <a href="<%= gossip_path(@gossip.id) %>" class="btn btn-dark mx-1">Retour</a>
            </div>
            <div class="btn-group mr-2" role="group">
              <button type="submit" class="btn btn-success mx-1">Modifier</button>
            </div>
            <div class="btn-group mr-2" role="group">
              <a href="<%= gossip_path(@gossip.id) %>" class="btn btn-danger mx-1" data-confirm="Êtes-vous sûrs de vouloir le supprimer ?" data-method="DELETE">Supprimer</a>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </body>
</html>

app/views/gossips/index.html.erb
<html>
  <head>
  </head>
  <body>

      <div class="jumbotron">
        <h1 class="display-3 text-center" style="color: #053557">My Gossip Project</h1>
        <p class="lead text-center pt-2">Ou la poésie de vos doux petits mots</p>
      </div>

    
    <div class="container py-5 text-center">
    <!-- CARTE DECK GOSSIP -->
      <div class="card-deck">
        <% Gossip.all.each do |gossip| %>
          <div class="col-lg-4 col-md-6 mb-3">
            <div class="card text-left my-3">

              <!-- CARTE BODY GOSSIP -->
              <div class="card-body">
                <h5 class="card-title bold">
                  <%= link_to "#{gossip.id}. #{gossip.title}", gossip_path(gossip.id) %>
                </h5>
                <p class="card-text"><%= gossip.content %></p>
              </div>

              <!-- CARTE FOOTER GOSSIP -->
              <div class="card-footer">
                <p class="small float-left text-muted pr-2">
                  <%= gossip.comments.count %> 
                  <a href="<%= gossip_path(gossip.id) %>">
                  <i class="far fa-comment-dots"></i></a>
                </p> 
                <p class="small float-left text-muted">
                  <%= gossip.likes.count %>
                  <% if current_user == nil %>
                    <%= link_to "<i class='far fa-heart'></i>".html_safe, gossip_likes_path(gossip.id), method: :post %>
                  <% else %>
                    <% pre_like = gossip.likes.find { |like| like.user_id == current_user.id} %>
                    <% if pre_like %>
                      <%= link_to "<i class='fas fa-heart'></i>".html_safe, gossip_like_path(gossip.id, pre_like), method: :delete %>
                    <% else %>
                      <%= link_to "<i class='far fa-heart'></i>".html_safe, gossip_likes_path(gossip.id), method: :post %>
                    <% end %>
                  <% end %>
                </p>

                <p class="small float-right text-muted">Posté par <%= link_to "#{gossip.user.first_name}", user_path(gossip.user.id) %></p>
              </div>

            </div>
          </div>
        <% end %>
      </div>
      <!-- CARTE DECK GOSSIP -->
    </div>
  </body>
</html>

app/views/gossips/new.html.erb
<html>
  <head>
  </head>
  <body>
    <% if @gossip.errors.any? %>
    <div class="container alert alert-danger mt-3 pt-3 pb-1" role="alert">
        <p>Nous n'avons pas réussi à créer le gossip pour la (ou les) raison(s) suivante(s) :</p>
        <ul>
          <% @gossip.errors.each_with_index do |message, i| %>
            <li><%= message[1] %></li>
          <% end %>
        </ul>
    </div>
    <% end %>
    <div class="container text-center mt-5">
      <h1 style="color: #053557">Créer ton propre Gossip ?</h1>
      <div class="m-5 px-5">
        <%= form_tag url_for(action: 'create'), method: "post" do %>

          <div class="form-group">
          <%= text_field_tag 'title', @gossip.title, class: 'form-control', placeholder: 'Titre' %>
          </div> 

          <div class="form-group">
          <%= text_area_tag 'content', @gossip.content, class: 'form-control', placeholder: 'Contenu' %>
          </div> 

          <div class="btn-toolbar flex-nowrap justify-content-end mt-4" role="toolbar" aria-label="Toolbar with button groups">
            <div class="btn-group mr-2" role="group">
              <a href="<%= gossips_path %>" class="btn btn-dark mx-1">Retour</a>
            </div>
            <div class="btn-group mr-2" role="group">
              <%= submit_tag "Créer", class: "btn btn-success mx-1" %> 
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </body>
</html>

app/views/gossips/show.html.erb
<html>
  <head>
  </head>
  <body>
    <div class="container px-5 my-5">
      <h1 style="color: #053557" class="text-center">Gossip n°<%= params['id']%></h1>
      <br>
      <div class="card">
        <div class="card-body text-center py-5">
          <h4 style="color: #053557; font-weight: 450;"><%= @gossip.title %></h4>
          <p><%= @gossip.content %></p>
        </div>
        <div class="card-footer">
          <p class="small float-left text-muted pr-2">
            <%= @gossip.comments.count %> 
            <a href="#">
            <i class="far fa-comment-dots"></i></a>
          </p> 
          <p class="small float-left text-muted">
            <%= @gossip.likes.count %>
              <% if current_user == nil %>
                <%= link_to "<i class='far fa-heart'></i>".html_safe, gossip_likes_path(@gossip.id), method: :post %>
              <% else %>
                <% pre_like = @gossip.likes.find { |like| like.user_id == current_user.id} %>
                <% if pre_like %>
                  <%= link_to "<i class='fas fa-heart'></i>".html_safe, gossip_like_path(@gossip.id, pre_like), method: :delete %>
                <% else %>
                  <%= link_to "<i class='far fa-heart'></i>".html_safe, gossip_likes_path(@gossip.id), method: :post %>
                <% end %>
              <% end %>
          </p>
          <p class="small text-right text-muted">
            Posté par <%= link_to "#{@gossip.user.first_name} #{@gossip.user.last_name}", user_path(@gossip.user.id) %> (<%= link_to "#{@gossip.user.city.name}", city_path(@gossip.user.city.id) %>), le <%= @gossip.created_at.strftime("%d/%m/%Y") %> à <%= @gossip.created_at.strftime("%H:%M") %>.
          </p>
        </div>
      </div>

      <div class="btn-toolbar flex-nowrap justify-content-end" role="toolbar" aria-label="Toolbar with button groups">
        <div class="btn-group mr-2" role="group">
          <a href="<%= gossips_path %>" class="btn btn-dark mt-3 mx-1">Retour</a>
        </div>
        <% if logged_in? && current_user?(@gossip.user) %>
          <div class="btn-group mr-2" role="group">
            <a href="<%= edit_gossip_path(@gossip.id) %>" class="btn btn-success mt-3 mx-1">Modifier</a>
          </div>
          <div class="btn-group mr-2" role="group">
            <a href="<%= gossip_path(@gossip.id) %>" class="btn btn-danger mt-3 mx-1" data-confirm="Êtes-vous sûrs de vouloir le supprimer ?" data-method="DELETE">Supprimer</a>
          </div>
        <% end %>
      </div>
    </div>

    <div class="container px-5 mb-5">
      <% if logged_in? %>
        <p class="small text-muted ml-2 mb-1"><a href="<%= user_path(current_user.id) %>"><span style="color: #053557"><%= current_user.full_name %></span></a> :</p>
        <%= form_tag url_for(:controller => "comments", :action => "create"), method: 'post' do %>
          <input id="gossip" name="gossip_id" type="hidden" value="<%=@gossip.id%>" />
          <div class="form-group">
          <%= text_area_tag 'content', @comment.content, class: 'form-control', placeholder: 'Commenter ce gossip' %>
          </div> 

          <div class="btn-group d-flex justify-content-end mb-3 mr-2" role="group">
            <%= submit_tag "Commenter", class: "btn btn-dark mx-1" %> 
          </div>
        <% end %>
      <% end %>

      <div class="mt-5">
        <% x = 1 %>
        <% @gossip.comments.each do |comment| %>
            <div class="card my-2">
              <div class="card-body<%= " text-right" if x % 2 == 0 %>">
                <p class="small text-muted mb-1">
                  Commenté par <%= link_to "#{comment.user.first_name} #{comment.user.last_name}", user_path(@gossip.user.id) %> (<%= link_to "#{comment.user.city.name}", city_path(comment.user.city.id) %>), le <%= comment.created_at.strftime("%d/%m/%Y") %> à <%= comment.created_at.strftime("%H:%M") %>. 
                  <% if current_user?(comment.user) %>
                  <a href="<%= edit_comment_path(comment.id) %>", style="color: green"><i class="far fa-edit ml-1"></i></a>
                  <a href="<%= comment_path(comment.id) %>", style="color: red", data-confirm="Êtes-vous sûrs de vouloir supprimer ce commentaire ?", data-method="DELETE"><i class="far fa-trash-alt"></i></a>
                  <% end %>
                </p>
                <p><%= comment.content %></p>
              </div>
            </div>
          <% x += 1 %>
        <% end %>
      </div>
    </div>
  </body>
</html>

app/views/users/new.html.erb
<html>
  <head>
  </head>

  <body>
    <% if @user.errors.any? %>
      <div class="alert alert-danger pt-3 pb-1 pl-5" role="alert">
          <p>Nous n'avons pas réussi à créer votre compte pour la (ou les) raison(s) suivante(s) :</p>
          <ul>
            <% @user.errors.each_with_index do |message, i| %>
              <li><%= message[1] %></li>
            <% end %>
          </ul>
      </div>
    <% end %>

    <div class="container py-5 text-center">
      <h1 style="color: #053557">Inscription</h1>

      <div class="m-5 px-5">
        <%= form_for @user, class: 'form-horizontal' do |f| %>
          <div class="form-group">
            <%= f.text_field :first_name, class: 'form-control', placeholder: 'Prénom' %> 
          </div>
          <div class="form-group">
            <%= f.text_field :last_name, class: 'form-control', placeholder: 'Nom' %>
          </div>
          <div class="form-group">
            <%= f.collection_select :city_id, City.all, :id, :name, {prompt: "Ville"}, {class: "form-control"} %>
          </div>
          <div class="form-group">
            <%= f.number_field :age, min: 18, max: 199, class: 'form-control', placeholder: 'Age' %>
          </div>
          <div class="form-group">
            <%= f.email_field :email, class: 'form-control', placeholder: 'Email' %>
          </div>
          <div class="form-group">
            <%= f.password_field :password, class: 'form-control', placeholder: 'Mot de passe' %>
          </div>
          <div class="form-group">
            <%= f.password_field :password_confirmation, class: 'form-control', placeholder: 'Confirmation de mot de passe' %>
          </div>
          <div class="btn-toolbar flex-nowrap justify-content-end mt-4" role="toolbar" aria-label="Toolbar with button groups">
            <div class="btn-group mr-2" role="group">
              <a href="<%= root_path %>" class="btn btn-dark mx-1">Retour</a>
            </div>
            <div class="btn-group mr-2" role="group">
              <button type="submit" class="btn btn-success mx-1">S'inscrire</button>
            </div>
          </div>
        <% end %>
      </div>

    </div>

  </body>

</html>

app/views/users/show.html.erb
<html>
  <head>
  </head>
  <body>
    <div class="container py-5 text-center">
      <% user = User.find(params['id']) %>
      <h1 style="color: #053557" class="pb-3">Profil de <%= user.first_name %> <%= user.last_name %></h1>
      <br/>
      
      <div class="card flex-row flex-wrap flex-lg-nowrap mx-5 p-3">
        <img class="m-auto p-1" src="https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Circle-icons-profile.svg/512px-Circle-icons-profile.svg.png" alt="profile picture" height="200px" width="200px">
        <div class="card-body text-left my-auto">
          <p><b style="color: #053557">Âge</b> : <%= user.age %></p>
          <p><b style="color: #053557">Ville</b> : <%= link_to "#{user.city.name}", city_path(user.city.id) %></p>
          <p><b style="color: #053557">Email</b> : <%= user.email %></p><br/>
          <p><b style="color: #053557">Description</b> :<br/>
            <%= user.description %>
          </p>
        </div>
      </div>
    </div>
  </body>
</html>