config/routes.rb
Rails.application.routes.draw do
  resources :gossips do
    resources :likes, only: [:new, :create, :destroy]
  end
  resources :comments


  resources :users, only: [:show, :new, :create]
  resources :sessions, only: [:new, :create, :destroy]
  resources :cities, only: [:show]
  
  root 'gossips#index'
  get '/welcome/:id', to: 'welcome#show', as: 'welcome'
  get '/contact', to: 'welcome#contact'
  get '/team', to: 'welcome#team'

  get '/users', to: 'users#new'
  get '/sessions', to: 'sessions#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users, dependent: :delete_all
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :gossip

  validates :user,
    presence: { message: "Nous n'avons pas pu trouvé l'utilisateur associé." }

  validates :gossip,
    presence: { message: "Nous n'avons pas pu trouvé le Gossip associé." }

  validates :content,
    presence: { message: "Contenu obligatoire." }
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :join_table_tag_gossips
  has_many :tags, through: :join_table_tag_gossips
  has_many :comments
  has_many :likes, dependent: :destroy

  validates :title,
    presence: { message: "Titre obligatoire." },
    length: { minimum: 4, maximum: 60, message: "Le titre ne peut pas faire moins de 3 caractères ni plus de 60 caractères."}
  validates :content,
    presence: { message: "Contenu obligatoire." }
end

app/models/join_table_tag_gossip.rb
class JoinTableTagGossip < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :gossip

  validates :user_id,
    :uniqueness => { :scope => :gossip_id, message: "Un like par gossip" }
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :recipient, class_name: "User"
  belongs_to :sender, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :join_table_tag_gossips
  has_many :gossips, through: :join_table_tag_gossips
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :gossips
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
  has_many :comments
  has_many :likes, dependent: :destroy

  has_secure_password

  validates :first_name,
    presence: { message: "Prénom obligatoire." }

  validates :last_name,
    presence: { message: "Nom obligatoire." }

  validates :age,
    presence: { message: "Age obligatoire." }

  validates :password,
    presence: { message: "Mot de passe obligatoire." },
    length: { minimum: 6, too_short: "Mot de passe trop court." }

  validates :email,
    presence: { message: "Email obligatoire." },
    uniqueness: { message: "Email déjà pris." },
    format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "Format d'email invalide." }

  def full_name
    "#{first_name} #{last_name}"
  end

  def remember(remember_token)
    remember_digest = BCrypt::Password.create(remember_token)
    self.update(remember_digest: remember_digest)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  before_action :find_like, only: [:destroy]

  def new
    @like = Like.new
  end

  def create
    @gossip = Gossip.find(params[:gossip_id])
    @like = Like.new(gossip_id: params[:gossip_id], user: current_user)
  
    if @like.save
      redirect_to request.referrer
    else
      redirect_to request.referrer
    end
  end

  def destroy
    @like.destroy
    redirect_to request.referrer
  end

  private

  def find_like
    @gossip = Gossip.find(params[:gossip_id])
    @like = @gossip.likes.find(params[:id])
  end

  def already_liked?
    Like.where(user_id: current_user.id, gossip_id: params[:gossip_id]).exists?
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user_params = params.require(:user).permit(:first_name, :last_name, :age, :city_id, :email, :password, :password_confirmation)
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      remember(@user)
      flash[:success] = "Votre compte a été créé avec succès !"
      redirect_to root_path
    else
      render :new
    end
  end
  
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dynamic_pages_helper.rb
module DynamicPagesHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    if session[:user_id]

      current_user = User.find_by(id: session[:user_id])

    elsif cookies[:user_id]

      user = User.find_by(id: cookies[:user_id])

      if user && BCrypt::Password.new(user.remember_digest).is_password?(cookies[:remember_token])
        log_in user
        current_user = user
      end

    end
  end

   def log_in(user)
    session[:user_id] = user.id
  end

  def logged_in?
    session[:user_id]
  end

  def only_signed_in
    if !logged_in?
      flash[:danger] = "Vous devez être connecté pour cela."
      redirect_to new_session_path
    end
  end

  def current_user?(user)
    user == current_user
  end
  
  def remember(user)
    remember_token = SecureRandom.urlsafe_base64

    user.remember(remember_token)

    cookies.permanent[:user_id] = user.id
    cookies.permanent[:remember_token] = remember_token
  end

  def forget(user)
    user.update(remember_digest: nil)
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out(user)
    session.delete(:user_id)
    forget(user)
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Gossip Project</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/805bee8c95.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #053557;">
      <a class="navbar-brand" href="/">My Gossip Project</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/">Accueil</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/team">Équipe</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/contact">Contact</a>
          </li>
        </ul>

        <form class="form-inline">
          <ul class="navbar-nav mr-auto">
            <% if current_user %>
              <li class="nav-item">
                <a class="btn btn-sm btn-outline-info my-1 mr-2" href=" <%= user_path(current_user.id) %>" role="button">Profil</a>
              </li>
              <li class="nav-item">
                <%= link_to "Déconnexion", session_path(session.id), method: :delete, class: "btn btn-sm btn-outline-info my-1 mr-2" %>
              </li>
            <% else %>
              <li class="nav-item">
                <a class="btn btn-sm btn-outline-info my-1 mr-2" href=" <%= new_user_path %>" role="button">S'inscrire</a>
              </li>
              <li class="nav-item">
                <a class="btn btn-sm btn-outline-info my-1 mr-2" href=" <%= new_session_path %>" role="button">Connexion</a>
              </li>
            <% end %>
            <li class="nav-item">
              <a class="btn btn-sm btn-outline-light my-1" href=" <%= new_gossip_path %>" role="button">Nouveau Gossip</a>
            </li>
          </ul>
        </form>
      </div>
    </nav>

    <% flash.each do |name, message| %>
    <div class="alert alert-<%= name %> text-center mb-0"><%= message %></div>
    <% end %>

    <%= yield %>
    <script src="https://code.jquery.com/jquery-2.1.3.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>  
    
  </body>
</html>